# LINK: https://developer.confluent.io/confluent-tutorials/kafka-on-docker/

# ### Navigate to directory
# cd /opt/kafka/bin

# ### Create Topic
# ./kafka-topics.sh --create --topic my-topic --bootstrap-server broker:29092

# ### List Topics
# ./kafka-topics.sh --list --bootstrap-server broker:29092

# ### Describe Topic
# ./kafka-topics.sh --describe --topic my-topic --bootstrap-server broker:29092

# ### Delete Topic
# ./kafka-topics.sh --delete --topic my-topic --bootstrap-server broker:29092

# ### Produce Message
# ./kafka-console-producer.sh --topic my-topic --bootstrap-server broker:29092

# ### Consume Message
# ./kafka-console-consumer.sh --topic my-topic --from-beginning --bootstrap-server broker:29092

services:
  broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
